--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Xenophilicy/MaxEnchants 
build-by-default: true
branches:
- master
- PM4
projects:
  MaxEnchants:
    path: ""
    lint:
      phpstan: false
...
